export const goodsListConstants = {
    GET_ALL_GOODS_REQUEST: 'GET_ALL_GOODS_REQUEST',
    GET_ALL_GOODS_SUCCESS: 'GET_ALL_GOODS_SUCCESS',
    GET_ALL_GOODS_ERROR: 'GET_ALL_GOODS_ERROR',

    GET_ALL_GOODS_FROM_STORAGE: 'GET_ALL_GOODS_FROM_STORAGE',

    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
};